#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Text.RegularExpressions;
using StellarNet.Lite.Shared.Core;
using StellarNet.Lite.Shared.Infrastructure;
using UnityEditor;
using UnityEngine;

namespace StellarNet.Lite.Editor
{
    [InitializeOnLoad]
    public static class LiteProtocolScanner
    {
        #region 常量路径

        private const string GeneratedRootPath = "Assets/StellarNetLiteGenerated";
        private const string ProtocolIdsFolderPath = GeneratedRootPath + "/MsgIds";
        private const string ProtocolMetaFolderPath = GeneratedRootPath + "/Meta";
        private const string ComponentConstFolderPath = GeneratedRootPath + "/Components";
        private const string BinderRoomFolderPath = GeneratedRootPath + "/RoomBinders";
        private const string BinderModuleFolderPath = GeneratedRootPath + "/ModuleBinders";
        private const string MsgIdAggregateOutputPath = GeneratedRootPath + "/MsgIdConst.cs";
        private const string ComponentAggregateOutputPath = GeneratedRootPath + "/ComponentIdConst.cs";
        private const string MessageMetaAggregateOutputPath = GeneratedRootPath + "/AutoMessageMetaRegistry.cs";
        private const string RegistryAggregateOutputPath = GeneratedRootPath + "/AutoRegistry.cs";
        private const string AutoGeneratedFeatureMarkerPrefix = "// [AutoGeneratedFeatureKey]";

        #endregion

        #region 状态与结构

        private enum ScanResultState : byte
        {
            NoChange = 0,
            Changed = 1,
            Failed = 2
        }

        private sealed class MethodMeta
        {
            public string MethodName;
            public string MsgFullName;
            public int MsgId;
            public string FeatureKey;
        }

        private sealed class ClassMeta
        {
            public int Id;
            public string Name;
            public string SafeVarName;
            public string FullName;
            public string DisplayName;
            public string FeatureKey;
            public readonly List<MethodMeta> Methods = new List<MethodMeta>();
        }

        private sealed class ProtocolMeta
        {
            public int Id;
            public string SafeName;
            public string FullTypeName;
            public NetScope Scope;
            public NetDir Dir;
            public string FeatureKey;
        }

        private sealed class GeneratedFileRecord
        {
            public string Path;
            public string Content;
        }

        static LiteProtocolScanner()
        {
            RunScanAndGenerate(false);
        }

        #endregion

        #region 菜单入口

        [MenuItem("StellarNetLite/重新生成协议与组件常量表")]
        public static void ManualRun() => RunScanAndGenerate(false);

        [MenuItem("StellarNetLite/强制重新生成协议与组件常量表")]
        public static void ForceRun() => RunScanAndGenerate(true);

        #endregion

        #region 内置类型名

        private static readonly Dictionary<Type, string> BuiltInTypeNames = new Dictionary<Type, string>
        {
            { typeof(void), "void" }, { typeof(bool), "bool" }, { typeof(byte), "byte" }, { typeof(sbyte), "sbyte" },
            { typeof(char), "char" }, { typeof(decimal), "decimal" }, { typeof(double), "double" }, { typeof(float), "float" },
            { typeof(int), "int" }, { typeof(uint), "uint" }, { typeof(long), "long" }, { typeof(ulong), "ulong" },
            { typeof(object), "object" }, { typeof(short), "short" }, { typeof(ushort), "ushort" }, { typeof(string), "string" }
        };

        #endregion

        #region 主流程

        private static void RunScanAndGenerate(bool forceWrite)
        {
            ScanResultState protocolResult = ScanAndGenerateProtocols(forceWrite);
            ScanResultState componentResult = ScanAndGenerateComponentsAndRegistry(forceWrite);

            if (protocolResult == ScanResultState.Failed || componentResult == ScanResultState.Failed)
            {
                NetLogger.LogError("LiteProtocolScanner", "自动装配代码生成失败。");
                return;
            }

            if (protocolResult == ScanResultState.NoChange && componentResult == ScanResultState.NoChange && !forceWrite) return;

            AssetDatabase.Refresh();
            NetLogger.LogInfo("LiteProtocolScanner", forceWrite ? "分片自动装配代码已强制重新生成并应用。" : "分片自动装配代码已重新生成并应用。");
        }

        #endregion

        #region 类型工具

        private static string GetCSharpTypeName(Type type)
        {
            if (type == null) return "void";
            if (type.IsByRef) return "ref " + GetCSharpTypeName(type.GetElementType());
            if (type.IsPointer) return GetCSharpTypeName(type.GetElementType()) + "*";
            if (type.IsGenericParameter) return type.Name;
            if (BuiltInTypeNames.TryGetValue(type, out string builtInName)) return builtInName;
            if (type.IsArray) return GetCSharpTypeName(type.GetElementType()) + $"[{new string(',', type.GetArrayRank() - 1)}]";

            if (type.IsGenericType)
            {
                string genericName = type.GetGenericTypeDefinition().FullName ?? type.Name;
                int tickIndex = genericName.IndexOf('`');
                if (tickIndex >= 0) genericName = genericName.Substring(0, tickIndex);
                genericName = genericName.Replace('+', '.');
                string[] argNames = type.GetGenericArguments().Select(GetCSharpTypeName).ToArray();
                return $"{genericName}<{string.Join(", ", argNames)}>";
            }

            return !string.IsNullOrEmpty(type.FullName) ? type.FullName.Replace('+', '.') : type.Name;
        }

        private static string SanitizeIdentifier(string name)
        {
            if (string.IsNullOrEmpty(name)) return "Unknown";
            string safe = Regex.Replace(name, @"[^a-zA-Z0-9_]", "_");
            if (string.IsNullOrEmpty(safe)) return "Unknown";
            return char.IsDigit(safe[0]) ? "_" + safe : safe;
        }

        private static string EscapeStringLiteral(string value) =>
            string.IsNullOrEmpty(value) ? string.Empty : value.Replace("\\", "\\\\").Replace("\"", "\\\"");

        private static string GetFeatureKeyByType(Type type)
        {
            if (type == null) return "Unknown";
            string featureKey = GetFeatureKeyFromSourceHeader(type);
            return !string.IsNullOrEmpty(featureKey) ? SanitizeIdentifier(featureKey) : GetFeatureKeyByNamespaceFallback(type);
        }

        private static string GetFeatureKeyFromSourceHeader(Type type)
        {
            MonoScript monoScript = FindMonoScriptByType(type);
            if (monoScript == null) return string.Empty;

            string fullPath = AssetPathToFullPath(AssetDatabase.GetAssetPath(monoScript));
            if (string.IsNullOrEmpty(fullPath) || !File.Exists(fullPath)) return string.Empty;

            string[] lines = File.ReadAllLines(fullPath);
            for (int i = 0; i < Math.Min(12, lines.Length); i++)
            {
                string trimmed = lines[i]?.Trim();
                if (trimmed != null && trimmed.StartsWith(AutoGeneratedFeatureMarkerPrefix, StringComparison.Ordinal))
                {
                    return trimmed.Substring(AutoGeneratedFeatureMarkerPrefix.Length).Trim();
                }
            }

            return string.Empty;
        }

        private static MonoScript FindMonoScriptByType(Type type)
        {
            string[] guids = AssetDatabase.FindAssets($"{type.Name} t:MonoScript");
            foreach (string guid in guids)
            {
                MonoScript script = AssetDatabase.LoadAssetAtPath<MonoScript>(AssetDatabase.GUIDToAssetPath(guid));
                if (script != null && script.GetClass() == type) return script;
            }

            return null;
        }

        private static string GetFeatureKeyByNamespaceFallback(Type type)
        {
            string ns = type.Namespace ?? string.Empty;
            if (string.IsNullOrEmpty(ns)) return SanitizeIdentifier(type.Name);

            string[] segments = ns.Split('.');
            for (int i = 0; i < segments.Length - 1; i++)
            {
                if ((segments[i] == "Shared" && segments[i + 1] == "Protocol") ||
                    (segments[i] == "Server" && (segments[i + 1] == "Components" || segments[i + 1] == "Modules")) ||
                    (segments[i] == "Client" && (segments[i + 1] == "Components" || segments[i + 1] == "Modules")))
                {
                    return i - 1 >= 0 ? SanitizeIdentifier(segments[i - 1]) : SanitizeIdentifier(type.Name);
                }
            }

            return segments.Length >= 2 ? SanitizeIdentifier(segments[segments.Length - 1]) : SanitizeIdentifier(type.Name);
        }

        private static string AssetPathToFullPath(string assetPath)
        {
            if (string.IsNullOrEmpty(assetPath)) return string.Empty;
            string normalized = NormalizePath(assetPath);
            if (!normalized.StartsWith("Assets", StringComparison.Ordinal)) return string.Empty;

            DirectoryInfo root = Directory.GetParent(Application.dataPath);
            return root != null ? NormalizePath($"{root.FullName.Replace("\\", "/")}/{normalized}") : string.Empty;
        }

        #endregion

        #region 协议扫描与生成

        private static ScanResultState ScanAndGenerateProtocols(bool forceWrite)
        {
            var types = TypeCache.GetTypesWithAttribute<NetMsgAttribute>();
            var protocolList = new List<ProtocolMeta>();
            var idMap = new Dictionary<int, string>();
            var safeNameMap = new Dictionary<string, string>();
            bool hasConflict = false;

            foreach (Type type in types)
            {
                NetMsgAttribute attr = type.GetCustomAttribute<NetMsgAttribute>();
                if (attr == null) continue;

                string fullTypeName = GetCSharpTypeName(type);
                string safeName = SanitizeIdentifier(type.Name);

                if (idMap.ContainsKey(attr.Id) || safeNameMap.ContainsKey(safeName))
                {
                    NetLogger.LogError("LiteProtocolScanner", $"MsgId 或 Const 命名冲突: {attr.Id} / {safeName}");
                    hasConflict = true;
                    continue;
                }

                idMap.Add(attr.Id, fullTypeName);
                safeNameMap.Add(safeName, fullTypeName);

                protocolList.Add(new ProtocolMeta
                {
                    Id = attr.Id, SafeName = safeName, FullTypeName = fullTypeName, Scope = attr.Scope, Dir = attr.Dir,
                    FeatureKey = GetFeatureKeyByType(type)
                });
            }

            if (hasConflict) return ScanResultState.Failed;

            var protocolFiles = BuildProtocolShardFiles(protocolList);
            bool shardChanged = WriteGeneratedShardSet(ProtocolIdsFolderPath,
                protocolFiles.Where(f => f.Path.StartsWith(ProtocolIdsFolderPath)).ToList(), forceWrite);
            bool metaShardChanged = WriteGeneratedShardSet(ProtocolMetaFolderPath,
                protocolFiles.Where(f => f.Path.StartsWith(ProtocolMetaFolderPath)).ToList(), forceWrite);
            bool aggregateMsgChanged = GenerateAggregateMsgIdConstFile(protocolList, forceWrite);
            bool aggregateMetaChanged = GenerateAggregateMessageMetaRegistryFile(protocolList, forceWrite);

            return (shardChanged || metaShardChanged || aggregateMsgChanged || aggregateMetaChanged)
                ? ScanResultState.Changed
                : ScanResultState.NoChange;
        }

        private static List<GeneratedFileRecord> BuildProtocolShardFiles(List<ProtocolMeta> protocolList)
        {
            var result = new List<GeneratedFileRecord>();
            var grouped = protocolList.OrderBy(p => p.Id).GroupBy(p => string.IsNullOrEmpty(p.FeatureKey) ? "Unknown" : p.FeatureKey);

            foreach (var group in grouped)
            {
                string featureKey = SanitizeIdentifier(group.Key);
                var groupList = group.OrderBy(p => p.Id).ToList();

                var idSb = new StringBuilder();
                var metaSb1 = new StringBuilder();
                var metaSb2 = new StringBuilder();

                foreach (var proto in groupList)
                {
                    idSb.AppendLine($"        public const int {proto.SafeName} = {proto.Id};");
                    metaSb1.AppendLine(
                        $"            target[typeof({proto.FullTypeName})] = new NetMessageMeta({proto.Id}, NetScope.{proto.Scope}, NetDir.{proto.Dir});");
                    metaSb2.AppendLine($"            target[{proto.Id}] = typeof({proto.FullTypeName});");
                }

                result.Add(new GeneratedFileRecord
                {
                    Path = $"{ProtocolIdsFolderPath}/Generated_{featureKey}_MsgIds.cs",
                    Content = $@"namespace StellarNet.Lite.Shared.Generated.Protocol.MsgIds
{{
    public static class Generated_{featureKey}_MsgIds
    {{
{idSb}    }}
}}"
                });

                result.Add(new GeneratedFileRecord
                {
                    Path = $"{ProtocolMetaFolderPath}/Generated_{featureKey}_MessageMeta.cs",
                    Content = $@"using System;
using System.Collections.Generic;
using StellarNet.Lite.Shared.Core;

namespace StellarNet.Lite.Shared.Generated.Protocol.Meta
{{
    public static class Generated_{featureKey}_MessageMeta
    {{
        public static void AppendTypeToMeta(Dictionary<Type, NetMessageMeta> target)
        {{
            if (target == null) return;
{metaSb1}        }}

        public static void AppendMsgIdToType(Dictionary<int, Type> target)
        {{
            if (target == null) return;
{metaSb2}        }}
    }}
}}"
                });
            }

            return result;
        }

        private static bool GenerateAggregateMsgIdConstFile(List<ProtocolMeta> protocolList, bool forceWrite)
        {
            var sb = new StringBuilder();
            foreach (var proto in protocolList.OrderBy(p => p.Id))
            {
                sb.AppendLine($"        public const int {proto.SafeName} = {proto.Id};");
            }

            string content = $@"namespace StellarNet.Lite.Shared.Protocol
{{
    public static class MsgIdConst
    {{
{sb}    }}
}}";
            return WriteToFile(MsgIdAggregateOutputPath, content, forceWrite);
        }

        private static bool GenerateAggregateMessageMetaRegistryFile(List<ProtocolMeta> protocolList, bool forceWrite)
        {
            var featureKeys = protocolList.Select(p => string.IsNullOrEmpty(p.FeatureKey) ? "Unknown" : SanitizeIdentifier(p.FeatureKey)).Distinct()
                .OrderBy(p => p).ToList();

            var sb1 = new StringBuilder();
            var sb2 = new StringBuilder();

            foreach (var key in featureKeys)
            {
                sb1.AppendLine($"            Generated_{key}_MessageMeta.AppendTypeToMeta(result);");
                sb2.AppendLine($"            Generated_{key}_MessageMeta.AppendMsgIdToType(result);");
            }

            string content = $@"using System;
using System.Collections.Generic;
using StellarNet.Lite.Shared.Core;
using StellarNet.Lite.Shared.Generated.Protocol.Meta;

namespace StellarNet.Lite.Shared.Protocol
{{
    public static class AutoMessageMetaRegistry
    {{
        public static readonly Dictionary<Type, NetMessageMeta> TypeToMeta = BuildTypeToMeta();
        public static readonly Dictionary<int, Type> MsgIdToType = BuildMsgIdToType();

        private static Dictionary<Type, NetMessageMeta> BuildTypeToMeta()
        {{
            var result = new Dictionary<Type, NetMessageMeta>();
{sb1}            return result;
        }}

        private static Dictionary<int, Type> BuildMsgIdToType()
        {{
            var result = new Dictionary<int, Type>();
{sb2}            return result;
        }}
    }}
}}";
            return WriteToFile(MessageMetaAggregateOutputPath, content, forceWrite);
        }

        #endregion

        #region 组件与注册扫描

        private static ScanResultState ScanAndGenerateComponentsAndRegistry(bool forceWrite)
        {
            var serverComps = new List<ClassMeta>();
            var clientComps = new List<ClassMeta>();
            var serverMods = new List<ClassMeta>();
            var clientMods = new List<ClassMeta>();

            var serverGlobalMsgIds = new Dictionary<int, string>();
            var serverRoomMsgIds = new Dictionary<int, string>();
            var clientGlobalMsgIds = new Dictionary<int, string>();
            var clientRoomMsgIds = new Dictionary<int, string>();

            bool hasFatalError = false;

            foreach (Type type in TypeCache.GetTypesWithAttribute<RoomComponentAttribute>())
            {
                var attr = type.GetCustomAttribute<RoomComponentAttribute>();
                if (attr == null) continue;

                var meta = new ClassMeta
                {
                    Id = attr.Id, Name = attr.Name, SafeVarName = SanitizeIdentifier(GetCSharpTypeName(type)), FullName = GetCSharpTypeName(type),
                    DisplayName = attr.DisplayName, FeatureKey = GetFeatureKeyByType(type)
                };

                bool isServer = type.IsSubclassOf(typeof(StellarNet.Lite.Server.Core.ServerRoomComponent));
                bool isClient = type.IsSubclassOf(typeof(StellarNet.Lite.Client.Core.ClientRoomComponent));

                if (!isServer && !isClient)
                {
                    hasFatalError = true;
                    continue;
                }

                if (!ScanMethods(type, isServer, meta, isServer ? serverRoomMsgIds : clientRoomMsgIds)) hasFatalError = true;

                if (isServer) serverComps.Add(meta);
                else clientComps.Add(meta);
            }

            foreach (Type type in TypeCache.GetTypesWithAttribute<ServerModuleAttribute>())
            {
                var attr = type.GetCustomAttribute<ServerModuleAttribute>();
                if (attr == null) continue;

                var meta = new ClassMeta
                {
                    Name = attr.Name, SafeVarName = SanitizeIdentifier(GetCSharpTypeName(type)), FullName = GetCSharpTypeName(type),
                    DisplayName = attr.DisplayName, FeatureKey = GetFeatureKeyByType(type)
                };

                if (!ScanMethods(type, true, meta, serverGlobalMsgIds)) hasFatalError = true;
                serverMods.Add(meta);
            }

            foreach (Type type in TypeCache.GetTypesWithAttribute<ClientModuleAttribute>())
            {
                var attr = type.GetCustomAttribute<ClientModuleAttribute>();
                if (attr == null) continue;

                var meta = new ClassMeta
                {
                    Name = attr.Name, SafeVarName = SanitizeIdentifier(GetCSharpTypeName(type)), FullName = GetCSharpTypeName(type),
                    DisplayName = attr.DisplayName, FeatureKey = GetFeatureKeyByType(type)
                };

                if (!ScanMethods(type, false, meta, clientGlobalMsgIds)) hasFatalError = true;
                clientMods.Add(meta);
            }

            if (hasFatalError) return ScanResultState.Failed;

            var mergedComps = MergeUniqueComponentsById(serverComps, clientComps);

            bool c1 = WriteGeneratedShardSet(ComponentConstFolderPath, BuildComponentConstShardFiles(mergedComps), forceWrite);
            bool c2 = WriteGeneratedShardSet(BinderRoomFolderPath, BuildRoomBinderShardFiles(serverComps, clientComps, mergedComps), forceWrite);
            bool c3 = WriteGeneratedShardSet(BinderModuleFolderPath, BuildModuleBinderShardFiles(serverMods, clientMods), forceWrite);
            bool c4 = GenerateAggregateComponentConstFile(mergedComps, forceWrite);
            bool c5 = GenerateAggregateAutoRegistryFile(serverComps, clientComps, serverMods, clientMods, mergedComps, forceWrite);

            return (c1 || c2 || c3 || c4 || c5) ? ScanResultState.Changed : ScanResultState.NoChange;
        }

        private static bool ScanMethods(Type type, bool isServer, ClassMeta meta, Dictionary<int, string> msgIdTracker)
        {
            bool isSafe = true;
            foreach (MethodInfo method in type.GetMethods(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic))
            {
                if (method.GetCustomAttribute<NetHandlerAttribute>() == null) continue;

                var parameters = method.GetParameters();
                Type msgType = isServer
                    ? (parameters.Length == 2 ? parameters[1].ParameterType : null)
                    : (parameters.Length == 1 ? parameters[0].ParameterType : null);

                if (msgType == null)
                {
                    isSafe = false;
                    continue;
                }

                var netMsgAttr = msgType.GetCustomAttribute<NetMsgAttribute>();
                if (netMsgAttr == null)
                {
                    isSafe = false;
                    continue;
                }

                if (msgIdTracker.ContainsKey(netMsgAttr.Id))
                {
                    isSafe = false;
                    continue;
                }

                msgIdTracker.Add(netMsgAttr.Id, $"{type.FullName}.{method.Name}");

                meta.Methods.Add(new MethodMeta
                {
                    MethodName = method.Name, MsgFullName = GetCSharpTypeName(msgType), MsgId = netMsgAttr.Id,
                    FeatureKey = GetFeatureKeyByType(msgType)
                });
            }

            return isSafe;
        }

        private static List<ClassMeta> MergeUniqueComponentsById(List<ClassMeta> serverComps, List<ClassMeta> clientComps)
        {
            var merged = new List<ClassMeta>();
            var idMap = new HashSet<int>();
            foreach (var meta in serverComps.Concat(clientComps).OrderBy(c => c.Id))
            {
                if (idMap.Add(meta.Id)) merged.Add(meta);
            }

            return merged;
        }

        #endregion

        #region 组件常量分片

        private static List<GeneratedFileRecord> BuildComponentConstShardFiles(List<ClassMeta> compList)
        {
            var result = new List<GeneratedFileRecord>();
            foreach (var group in compList.OrderBy(p => p.Id).GroupBy(c => string.IsNullOrEmpty(c.FeatureKey) ? "Unknown" : c.FeatureKey))
            {
                string featureKey = SanitizeIdentifier(group.Key);
                var sb = new StringBuilder();

                foreach (var comp in group.OrderBy(c => c.Id))
                    sb.AppendLine($"        public const int {SanitizeIdentifier(comp.Name)} = {comp.Id};");

                result.Add(new GeneratedFileRecord
                {
                    Path = $"{ComponentConstFolderPath}/Generated_{featureKey}_ComponentIds.cs",
                    Content = $@"namespace StellarNet.Lite.Shared.Generated.Protocol.Components
{{
    public static class Generated_{featureKey}_ComponentIds
    {{
{sb}    }}
}}"
                });
            }

            return result;
        }

        private static bool GenerateAggregateComponentConstFile(List<ClassMeta> compList, bool forceWrite)
        {
            var sb = new StringBuilder();
            foreach (var comp in compList.OrderBy(p => p.Id)) sb.AppendLine($"        public const int {SanitizeIdentifier(comp.Name)} = {comp.Id};");

            string content = $@"namespace StellarNet.Lite.Shared.Protocol
{{
    public static class ComponentIdConst
    {{
{sb}    }}
}}";
            return WriteToFile(ComponentAggregateOutputPath, content, forceWrite);
        }

        #endregion

        #region RoomBinder 分片

        private static List<GeneratedFileRecord> BuildRoomBinderShardFiles(List<ClassMeta> serverComps, List<ClassMeta> clientComps,
            List<ClassMeta> mergedComps)
        {
            var result = new List<GeneratedFileRecord>();
            var featureKeys = mergedComps.Select(c => string.IsNullOrEmpty(c.FeatureKey) ? "Unknown" : SanitizeIdentifier(c.FeatureKey)).Distinct()
                .OrderBy(k => k).ToList();

            foreach (string featureKey in featureKeys)
            {
                var featureMergedComps = mergedComps.Where(c => SanitizeIdentifier(c.FeatureKey) == featureKey).OrderBy(c => c.Id).ToList();
                var featureServerComps = serverComps.Where(c => SanitizeIdentifier(c.FeatureKey) == featureKey).OrderBy(c => c.Id).ToList();
                var featureClientComps = clientComps.Where(c => SanitizeIdentifier(c.FeatureKey) == featureKey).OrderBy(c => c.Id).ToList();

                var metaSb = new StringBuilder();
                foreach (var comp in featureMergedComps)
                    metaSb.AppendLine(
                        $"            target.Add(new RoomComponentMeta {{ Id = {comp.Id}, Name = \"{EscapeStringLiteral(comp.Name)}\", DisplayName = \"{EscapeStringLiteral(comp.DisplayName)}\" }});");

                var sRegSb = new StringBuilder();
                var sBindSb = new StringBuilder();
                foreach (var comp in featureServerComps)
                {
                    sRegSb.AppendLine($"            ServerRoomFactory.Register({comp.Id}, () => new {comp.FullName}(serverApp));");

                    sBindSb.AppendLine($"                case {comp.FullName} c_{comp.Id}:");
                    foreach (var method in comp.Methods)
                    {
                        sBindSb.AppendLine($@"                    dispatcher.Register({method.MsgId}, (session, packet) => {{
                        if (deserializeFunc(packet.Payload, packet.PayloadOffset, packet.PayloadLength, typeof({method.MsgFullName})) is {method.MsgFullName} msg) {{
                            c_{comp.Id}.{method.MethodName}(session, msg);
                        }}
                    }});");
                    }

                    sBindSb.AppendLine("                    return true;");
                }

                var cRegSb = new StringBuilder();
                var cBindSb = new StringBuilder();
                foreach (var comp in featureClientComps)
                {
                    cRegSb.AppendLine($"            ClientRoomFactory.Register({comp.Id}, () => new {comp.FullName}(clientApp));");

                    cBindSb.AppendLine($"                case {comp.FullName} c_{comp.Id}:");
                    foreach (var method in comp.Methods)
                    {
                        cBindSb.AppendLine($@"                    dispatcher.Register({method.MsgId}, (packet) => {{
                        if (deserializeFunc(packet.Payload, packet.PayloadOffset, packet.PayloadLength, typeof({method.MsgFullName})) is {method.MsgFullName} msg) {{
                            c_{comp.Id}.{method.MethodName}(msg);
                        }}
                    }});");
                    }

                    cBindSb.AppendLine("                    return true;");
                }

                string content = $@"using System;
using System.Collections.Generic;
using StellarNet.Lite.Shared.Core;
using StellarNet.Lite.Server.Core;
using StellarNet.Lite.Client.Core;

namespace StellarNet.Lite.Shared.Generated.Binders.RoomComponents
{{
    public static class Generated_{featureKey}_RoomBinder
    {{
        public static void AppendRoomComponentMeta(List<RoomComponentMeta> target)
        {{
            if (target == null) return;
{metaSb}        }}

        public static void RegisterServerFactory(ServerApp serverApp)
        {{
            if (serverApp == null) return;
{sRegSb}        }}

        public static void RegisterClientFactory(ClientApp clientApp)
        {{
            if (clientApp == null) return;
{cRegSb}        }}

        public static bool TryBindServer(StellarNet.Lite.Server.Core.ServerRoomComponent comp, StellarNet.Lite.Server.Core.RoomDispatcher dispatcher, Func<byte[], int, int, Type, object> deserializeFunc)
        {{
            if (comp == null || dispatcher == null || deserializeFunc == null) return false;

            switch (comp)
            {{
{sBindSb}            }}
            return false;
        }}

        public static bool TryBindClient(StellarNet.Lite.Client.Core.ClientRoomComponent comp, StellarNet.Lite.Client.Core.ClientRoomDispatcher dispatcher, Func<byte[], int, int, Type, object> deserializeFunc)
        {{
            if (comp == null || dispatcher == null || deserializeFunc == null) return false;

            switch (comp)
            {{
{cBindSb}            }}
            return false;
        }}
    }}
}}";
                result.Add(new GeneratedFileRecord { Path = $"{BinderRoomFolderPath}/Generated_{featureKey}_RoomBinder.cs", Content = content });
            }

            return result;
        }

        #endregion

        #region ModuleBinder 分片

        private static List<GeneratedFileRecord> BuildModuleBinderShardFiles(List<ClassMeta> serverMods, List<ClassMeta> clientMods)
        {
            var result = new List<GeneratedFileRecord>();
            var featureKeys = serverMods.Concat(clientMods)
                .Select(m => string.IsNullOrEmpty(m.FeatureKey) ? "Unknown" : SanitizeIdentifier(m.FeatureKey)).Distinct().OrderBy(k => k).ToList();

            foreach (string featureKey in featureKeys)
            {
                var featureServerMods = serverMods.Where(m => SanitizeIdentifier(m.FeatureKey) == featureKey).OrderBy(m => m.FullName).ToList();
                var featureClientMods = clientMods.Where(m => SanitizeIdentifier(m.FeatureKey) == featureKey).OrderBy(m => m.FullName).ToList();

                var sRegSb = new StringBuilder();
                foreach (var mod in featureServerMods)
                {
                    sRegSb.AppendLine($"            var mod_{mod.SafeVarName} = new {mod.FullName}(serverApp);");
                    foreach (var method in mod.Methods)
                    {
                        sRegSb.AppendLine($@"            serverApp.GlobalDispatcher.Register({method.MsgId}, (session, packet) => {{
                if (deserializeFunc(packet.Payload, packet.PayloadOffset, packet.PayloadLength, typeof({method.MsgFullName})) is {method.MsgFullName} msg) {{
                    mod_{mod.SafeVarName}.{method.MethodName}(session, msg);
                }}
            }});");
                    }
                }

                var cRegSb = new StringBuilder();
                foreach (var mod in featureClientMods)
                {
                    cRegSb.AppendLine($"            var mod_{mod.SafeVarName} = new {mod.FullName}(clientApp);");
                    foreach (var method in mod.Methods)
                    {
                        cRegSb.AppendLine($@"            clientApp.GlobalDispatcher.Register({method.MsgId}, (packet) => {{
                if (deserializeFunc(packet.Payload, packet.PayloadOffset, packet.PayloadLength, typeof({method.MsgFullName})) is {method.MsgFullName} msg) {{
                    mod_{mod.SafeVarName}.{method.MethodName}(msg);
                }}
            }});");
                    }
                }

                string content = $@"using System;
using StellarNet.Lite.Server.Core;
using StellarNet.Lite.Client.Core;

namespace StellarNet.Lite.Shared.Generated.Binders.GlobalModules
{{
    public static class Generated_{featureKey}_ModuleBinder
    {{
        public static void RegisterServer(ServerApp serverApp, Func<byte[], int, int, Type, object> deserializeFunc)
        {{
            if (serverApp == null || deserializeFunc == null) return;
{sRegSb}        }}

        public static void RegisterClient(ClientApp clientApp, Func<byte[], int, int, Type, object> deserializeFunc)
        {{
            if (clientApp == null || deserializeFunc == null) return;
{cRegSb}        }}
    }}
}}";
                result.Add(new GeneratedFileRecord { Path = $"{BinderModuleFolderPath}/Generated_{featureKey}_ModuleBinder.cs", Content = content });
            }

            return result;
        }

        #endregion

        #region 聚合 AutoRegistry

        private static bool GenerateAggregateAutoRegistryFile(List<ClassMeta> serverComps, List<ClassMeta> clientComps, List<ClassMeta> serverMods,
            List<ClassMeta> clientMods, List<ClassMeta> mergedComps, bool forceWrite)
        {
            var roomFeatureKeys = mergedComps.Select(c => string.IsNullOrEmpty(c.FeatureKey) ? "Unknown" : SanitizeIdentifier(c.FeatureKey))
                .Distinct().OrderBy(k => k).ToList();
            var moduleFeatureKeys = serverMods.Concat(clientMods)
                .Select(m => string.IsNullOrEmpty(m.FeatureKey) ? "Unknown" : SanitizeIdentifier(m.FeatureKey)).Distinct().OrderBy(k => k).ToList();

            var metaSb = new StringBuilder();
            var sRegSb = new StringBuilder();
            var cRegSb = new StringBuilder();
            var sBindSb = new StringBuilder();
            var cBindSb = new StringBuilder();

            foreach (var key in roomFeatureKeys) metaSb.AppendLine($"            Generated_{key}_RoomBinder.AppendRoomComponentMeta(result);");

            foreach (var key in moduleFeatureKeys)
                sRegSb.AppendLine($"            Generated_{key}_ModuleBinder.RegisterServer(serverApp, deserializeFunc);");

            foreach (var key in roomFeatureKeys) sRegSb.AppendLine($"            Generated_{key}_RoomBinder.RegisterServerFactory(serverApp);");

            foreach (var key in roomFeatureKeys)
                sBindSb.AppendLine($"            if (Generated_{key}_RoomBinder.TryBindServer(comp, dispatcher, deserializeFunc)) return;");

            foreach (var key in moduleFeatureKeys)
                cRegSb.AppendLine($"            Generated_{key}_ModuleBinder.RegisterClient(clientApp, deserializeFunc);");

            foreach (var key in roomFeatureKeys) cRegSb.AppendLine($"            Generated_{key}_RoomBinder.RegisterClientFactory(clientApp);");

            foreach (var key in roomFeatureKeys)
                cBindSb.AppendLine($"            if (Generated_{key}_RoomBinder.TryBindClient(comp, dispatcher, deserializeFunc)) return;");

            string content = $@"using System;
using System.Collections.Generic;
using StellarNet.Lite.Shared.Core;
using StellarNet.Lite.Server.Core;
using StellarNet.Lite.Client.Core;
using StellarNet.Lite.Shared.Generated.Binders.RoomComponents;
using StellarNet.Lite.Shared.Generated.Binders.GlobalModules;

namespace StellarNet.Lite.Shared.Binders
{{
    public static class AutoRegistry
    {{
        public static readonly List<RoomComponentMeta> RoomComponentMetaList = BuildRoomComponentMetaList();

        private static List<RoomComponentMeta> BuildRoomComponentMetaList()
        {{
            var result = new List<RoomComponentMeta>();
{metaSb}            return result;
        }}

        public static void RegisterServer(ServerApp serverApp, Func<byte[], int, int, Type, object> deserializeFunc)
        {{
            if (serverApp == null || deserializeFunc == null) return;
            ServerRoomFactory.Clear();
{sRegSb}        }}

        public static void BindServerComponent(StellarNet.Lite.Server.Core.ServerRoomComponent comp, StellarNet.Lite.Server.Core.RoomDispatcher dispatcher, Func<byte[], int, int, Type, object> deserializeFunc)
        {{
            if (comp == null) return;
{sBindSb}        }}

        public static void RegisterClient(ClientApp clientApp, Func<byte[], int, int, Type, object> deserializeFunc)
        {{
            if (clientApp == null || deserializeFunc == null) return;
            ClientRoomFactory.Clear();
{cRegSb}        }}

        public static void BindClientComponent(StellarNet.Lite.Client.Core.ClientRoomComponent comp, StellarNet.Lite.Client.Core.ClientRoomDispatcher dispatcher, Func<byte[], int, int, Type, object> deserializeFunc)
        {{
            if (comp == null) return;
{cBindSb}        }}
    }}
}}";
            return WriteToFile(RegistryAggregateOutputPath, content, forceWrite);
        }

        #endregion

        #region 分片写入与清理

        private static bool WriteGeneratedShardSet(string folderPath, List<GeneratedFileRecord> records, bool forceWrite)
        {
            if (!Directory.Exists(folderPath)) Directory.CreateDirectory(folderPath);

            bool changed = false;
            var expectedPaths = new HashSet<string>(records.Select(r => NormalizePath(r.Path)));

            foreach (var oldFile in Directory.GetFiles(folderPath, "*.cs", SearchOption.TopDirectoryOnly))
            {
                string normalized = NormalizePath(oldFile);
                if (!expectedPaths.Contains(normalized))
                {
                    File.Delete(normalized);
                    if (File.Exists(normalized + ".meta")) File.Delete(normalized + ".meta");
                    changed = true;
                }
            }

            foreach (var record in records)
            {
                if (WriteToFile(record.Path, record.Content, forceWrite)) changed = true;
            }

            return changed;
        }

        private static string NormalizePath(string path) => string.IsNullOrEmpty(path) ? string.Empty : path.Replace("\\", "/");

        private static bool WriteToFile(string path, string newContent, bool forceWrite)
        {
            string normalizedPath = NormalizePath(path);
            string directory = Path.GetDirectoryName(normalizedPath);
            if (!Directory.Exists(directory)) Directory.CreateDirectory(directory);

            if (!forceWrite && File.Exists(normalizedPath) && File.ReadAllText(normalizedPath) == newContent) return false;

            File.WriteAllText(normalizedPath, newContent, Encoding.UTF8);
            return true;
        }

        #endregion
    }
}
#endif