#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Text.RegularExpressions;
using StellarNet.Lite.Shared.Core;
using StellarNet.Lite.Shared.Infrastructure;
using UnityEditor;

namespace StellarNet.Lite.Editor
{
    [InitializeOnLoad]
    public static class LiteProtocolScanner
    {
        #region 常量路径

        private const string GeneratedRootPath = "Assets/StellarNetLite/Runtime/Shared/Generated";
        private const string ProtocolIdsFolderPath = GeneratedRootPath + "/Protocol/MsgIds";
        private const string ProtocolMetaFolderPath = GeneratedRootPath + "/Protocol/Meta";
        private const string ComponentConstFolderPath = GeneratedRootPath + "/Protocol/Components";
        private const string BinderRoomFolderPath = GeneratedRootPath + "/Binders/RoomComponents";
        private const string BinderModuleFolderPath = GeneratedRootPath + "/Binders/GlobalModules";

        private const string MsgIdAggregateOutputPath = "Assets/StellarNetLite/Runtime/Shared/Protocol/Const/MsgIdConst.cs";
        private const string ComponentAggregateOutputPath = "Assets/StellarNetLite/Runtime/Shared/Protocol/Const/ComponentIdConst.cs";
        private const string MessageMetaAggregateOutputPath = "Assets/StellarNetLite/Runtime/Shared/Protocol/Const/AutoMessageMetaRegistry.cs";
        private const string RegistryAggregateOutputPath = "Assets/StellarNetLite/Runtime/Shared/Binders/AutoRegistry.cs";

        private const string AutoGeneratedFeatureMarkerPrefix = "// ScaffoldFeature:";

        #endregion

        #region 状态与结构

        private enum ScanResultState : byte
        {
            NoChange = 0,
            Changed = 1,
            Failed = 2
        }

        private sealed class MethodMeta
        {
            public string MethodName;
            public string MsgFullName;
            public int MsgId;
            public string FeatureKey;
        }

        private sealed class ClassMeta
        {
            public int Id;
            public string Name;
            public string SafeVarName;
            public string FullName;
            public string DisplayName;
            public string FeatureKey;
            public readonly List<MethodMeta> Methods = new List<MethodMeta>();
        }

        private sealed class ProtocolMeta
        {
            public int Id;
            public string SafeName;
            public string FullTypeName;
            public NetScope Scope;
            public NetDir Dir;
            public string FeatureKey;
        }

        private sealed class GeneratedFileRecord
        {
            public string Path;
            public string Content;
        }

        static LiteProtocolScanner()
        {
            RunScanAndGenerate();
        }

        #endregion

        #region 菜单入口

        [MenuItem("StellarNetLite/强制重新生成协议与组件常量表")]
        public static void ManualRun()
        {
            RunScanAndGenerate();
        }

        #endregion

        #region 内置类型名

        private static readonly Dictionary<Type, string> BuiltInTypeNames = new Dictionary<Type, string>
        {
            { typeof(void), "void" },
            { typeof(bool), "bool" },
            { typeof(byte), "byte" },
            { typeof(sbyte), "sbyte" },
            { typeof(char), "char" },
            { typeof(decimal), "decimal" },
            { typeof(double), "double" },
            { typeof(float), "float" },
            { typeof(int), "int" },
            { typeof(uint), "uint" },
            { typeof(long), "long" },
            { typeof(ulong), "ulong" },
            { typeof(object), "object" },
            { typeof(short), "short" },
            { typeof(ushort), "ushort" },
            { typeof(string), "string" }
        };

        #endregion

        #region 主流程

        private static void RunScanAndGenerate()
        {
            ScanResultState protocolResult = ScanAndGenerateProtocols();
            ScanResultState componentResult = ScanAndGenerateComponentsAndRegistry();

            bool hasFailure = protocolResult == ScanResultState.Failed || componentResult == ScanResultState.Failed;
            if (hasFailure)
            {
                NetLogger.LogError(
                    "LiteProtocolScanner",
                    $"自动装配代码生成失败。ProtocolResult:{protocolResult}, ComponentResult:{componentResult}");
                return;
            }

            bool hasChange = protocolResult == ScanResultState.Changed || componentResult == ScanResultState.Changed;
            if (!hasChange)
            {
                return;
            }

            AssetDatabase.Refresh();
            NetLogger.LogInfo("LiteProtocolScanner", "分片自动装配代码已重新生成并应用。");
        }

        #endregion

        #region 类型工具

        private static string GetCSharpTypeName(Type type)
        {
            if (type == null)
            {
                return "void";
            }

            if (type.IsByRef)
            {
                Type elementType = type.GetElementType();
                return "ref " + GetCSharpTypeName(elementType);
            }

            if (type.IsPointer)
            {
                Type elementType = type.GetElementType();
                return GetCSharpTypeName(elementType) + "*";
            }

            if (type.IsGenericParameter)
            {
                return type.Name;
            }

            if (BuiltInTypeNames.TryGetValue(type, out string builtInName))
            {
                return builtInName;
            }

            if (type.IsArray)
            {
                int rank = type.GetArrayRank();
                string commas = new string(',', rank - 1);
                Type elementType = type.GetElementType();
                return GetCSharpTypeName(elementType) + $"[{commas}]";
            }

            if (type.IsGenericType)
            {
                string genericName = type.GetGenericTypeDefinition().FullName;
                if (!string.IsNullOrEmpty(genericName))
                {
                    int tickIndex = genericName.IndexOf('`');
                    if (tickIndex >= 0)
                    {
                        genericName = genericName.Substring(0, tickIndex);
                    }

                    genericName = genericName.Replace('+', '.');
                }
                else
                {
                    genericName = type.Name;
                    int tickIndex = genericName.IndexOf('`');
                    if (tickIndex >= 0)
                    {
                        genericName = genericName.Substring(0, tickIndex);
                    }
                }

                Type[] genericArgs = type.GetGenericArguments();
                string[] argNames = new string[genericArgs.Length];
                for (int i = 0; i < genericArgs.Length; i++)
                {
                    argNames[i] = GetCSharpTypeName(genericArgs[i]);
                }

                return $"{genericName}<{string.Join(", ", argNames)}>";
            }

            if (!string.IsNullOrEmpty(type.FullName))
            {
                return type.FullName.Replace('+', '.');
            }

            return type.Name;
        }

        private static string SanitizeIdentifier(string name)
        {
            if (string.IsNullOrEmpty(name))
            {
                return "Unknown";
            }

            string safe = Regex.Replace(name, @"[^a-zA-Z0-9_]", "_");
            if (string.IsNullOrEmpty(safe))
            {
                return "Unknown";
            }

            if (char.IsDigit(safe[0]))
            {
                safe = "_" + safe;
            }

            return safe;
        }

        private static string EscapeStringLiteral(string value)
        {
            if (string.IsNullOrEmpty(value))
            {
                return string.Empty;
            }

            return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
        }

        private static string GetFeatureKeyByType(Type type)
        {
            if (type == null)
            {
                NetLogger.LogError("LiteProtocolScanner", "GetFeatureKey failed");
                return "Unknown";
            }

            string featureKey = GetFeatureKeyFromSourceHeader(type);
            if (!string.IsNullOrEmpty(featureKey))
            {
                return SanitizeIdentifier(featureKey);
            }

            return GetFeatureKeyByNamespaceFallback(type);
        }

        /// <summary>
        /// 我优先从源码头读取 ScaffoldFeature。
        /// 这样生成分片的边界直接绑定到脚手架模块本身，而不是再间接依赖命名空间布局。
        /// </summary>
        private static string GetFeatureKeyFromSourceHeader(Type type)
        {
            if (type == null)
            {
                NetLogger.LogError("LiteProtocolScanner", "GetFeatureKeyFromSourceHeader failed");
                return string.Empty;
            }

            MonoScript monoScript = FindMonoScriptByType(type);
            if (monoScript == null)
            {
                return string.Empty;
            }

            string assetPath = AssetDatabase.GetAssetPath(monoScript);
            if (string.IsNullOrEmpty(assetPath))
            {
                return string.Empty;
            }

            string fullPath = AssetPathToFullPath(assetPath);
            if (string.IsNullOrEmpty(fullPath))
            {
                return string.Empty;
            }

            if (!File.Exists(fullPath))
            {
                return string.Empty;
            }

            string[] lines = File.ReadAllLines(fullPath);
            if (lines == null || lines.Length == 0)
            {
                return string.Empty;
            }

            int maxCheckLineCount = Math.Min(12, lines.Length);
            for (int i = 0; i < maxCheckLineCount; i++)
            {
                string line = lines[i];
                if (string.IsNullOrWhiteSpace(line))
                {
                    continue;
                }

                string trimmed = line.Trim();
                if (!trimmed.StartsWith(AutoGeneratedFeatureMarkerPrefix, StringComparison.Ordinal))
                {
                    continue;
                }

                string rawFeature = trimmed.Substring(AutoGeneratedFeatureMarkerPrefix.Length).Trim();
                if (string.IsNullOrEmpty(rawFeature))
                {
                    continue;
                }

                return rawFeature;
            }

            return string.Empty;
        }

        /// <summary>
        /// 我只做“精确类型匹配”的脚本查找。
        /// 这里不用任何临时占位对象，也不做奇怪的 ScriptableObject 绕路，避免引入无意义 GC 和阅读噪音。
        /// </summary>
        private static MonoScript FindMonoScriptByType(Type type)
        {
            if (type == null)
            {
                NetLogger.LogError("LiteProtocolScanner", "FindMonoScriptByType failed");
                return null;
            }

            string[] guids = AssetDatabase.FindAssets($"{type.Name} t:MonoScript");
            if (guids == null || guids.Length == 0)
            {
                return null;
            }

            for (int i = 0; i < guids.Length; i++)
            {
                string guid = guids[i];
                if (string.IsNullOrEmpty(guid))
                {
                    continue;
                }

                string assetPath = AssetDatabase.GUIDToAssetPath(guid);
                if (string.IsNullOrEmpty(assetPath))
                {
                    continue;
                }

                MonoScript script = AssetDatabase.LoadAssetAtPath<MonoScript>(assetPath);
                if (script == null)
                {
                    continue;
                }

                Type scriptClass = script.GetClass();
                if (scriptClass == type)
                {
                    return script;
                }
            }

            return null;
        }

        private static string GetFeatureKeyByNamespaceFallback(Type type)
        {
            if (type == null)
            {
                NetLogger.LogError("LiteProtocolScanner", "GetFeatureKeyByNamespaceFallback failed");
                return "Unknown";
            }

            string ns = type.Namespace ?? string.Empty;
            if (string.IsNullOrEmpty(ns))
            {
                return SanitizeIdentifier(type.Name);
            }

            string[] segments = ns.Split('.');
            if (segments == null || segments.Length == 0)
            {
                return SanitizeIdentifier(type.Name);
            }

            for (int i = 0; i < segments.Length - 1; i++)
            {
                string current = segments[i];
                string next = segments[i + 1];

                bool isSharedPair = current == "Shared" && next == "Protocol";
                bool isServerPair = current == "Server" && (next == "Components" || next == "Modules");
                bool isClientPair = current == "Client" && (next == "Components" || next == "Modules");

                if (isSharedPair || isServerPair || isClientPair)
                {
                    if (i - 1 >= 0)
                    {
                        return SanitizeIdentifier(segments[i - 1]);
                    }

                    return SanitizeIdentifier(type.Name);
                }
            }

            if (segments.Length >= 2)
            {
                return SanitizeIdentifier(segments[segments.Length - 1]);
            }

            return SanitizeIdentifier(type.Name);
        }

        private static string AssetPathToFullPath(string assetPath)
        {
            if (string.IsNullOrEmpty(assetPath))
            {
                NetLogger.LogError("LiteProtocolScanner", "AssetPathToFullPath failed");
                return string.Empty;
            }

            string normalizedAssetPath = NormalizePath(assetPath);
            if (!normalizedAssetPath.StartsWith("Assets", StringComparison.Ordinal))
            {
                return string.Empty;
            }

            DirectoryInfo projectRoot = Directory.GetParent(UnityEngine.Application.dataPath);
            if (projectRoot == null)
            {
                NetLogger.LogError("LiteProtocolScanner", "AssetPathToFullPath failed");
                return string.Empty;
            }

            return NormalizePath($"{projectRoot.FullName.Replace("\\", "/")}/{normalizedAssetPath}");
        }

        #endregion

        #region 协议扫描与生成

        private static ScanResultState ScanAndGenerateProtocols()
        {
            var types = TypeCache.GetTypesWithAttribute<NetMsgAttribute>();
            var protocolList = new List<ProtocolMeta>();
            var idMap = new Dictionary<int, string>();
            var safeNameMap = new Dictionary<string, string>();
            var typeNameMap = new Dictionary<string, string>();
            bool hasConflict = false;

            foreach (Type type in types)
            {
                if (type == null)
                {
                    continue;
                }

                NetMsgAttribute attr = type.GetCustomAttribute<NetMsgAttribute>();
                if (attr == null)
                {
                    continue;
                }

                string fullTypeName = GetCSharpTypeName(type);
                string safeName = SanitizeIdentifier(type.Name);
                string featureKey = GetFeatureKeyByType(type);

                if (idMap.TryGetValue(attr.Id, out _))
                {
                    NetLogger.LogError("LiteProtocolScanner", $"MsgId conflict: {attr.Id}");
                    hasConflict = true;
                    continue;
                }

                if (safeNameMap.TryGetValue(safeName, out _))
                {
                    NetLogger.LogError("LiteProtocolScanner", $"Msg const conflict: {safeName}");
                    hasConflict = true;
                    continue;
                }

                if (typeNameMap.ContainsKey(fullTypeName))
                {
                    NetLogger.LogError("LiteProtocolScanner", "Msg type conflict");
                    hasConflict = true;
                    continue;
                }

                idMap.Add(attr.Id, fullTypeName);
                safeNameMap.Add(safeName, fullTypeName);
                typeNameMap.Add(fullTypeName, fullTypeName);

                protocolList.Add(new ProtocolMeta
                {
                    Id = attr.Id,
                    SafeName = safeName,
                    FullTypeName = fullTypeName,
                    Scope = attr.Scope,
                    Dir = attr.Dir,
                    FeatureKey = featureKey
                });
            }

            if (hasConflict)
            {
                return ScanResultState.Failed;
            }

            List<GeneratedFileRecord> protocolFiles = BuildProtocolShardFiles(protocolList);
            if (protocolFiles == null)
            {
                return ScanResultState.Failed;
            }

            bool shardChanged = WriteGeneratedShardSet(ProtocolIdsFolderPath, protocolFiles.Where(f => f.Path.StartsWith(ProtocolIdsFolderPath)).ToList());
            bool metaShardChanged = WriteGeneratedShardSet(ProtocolMetaFolderPath, protocolFiles.Where(f => f.Path.StartsWith(ProtocolMetaFolderPath)).ToList());

            bool aggregateMsgChanged = GenerateAggregateMsgIdConstFile(protocolList);
            bool aggregateMetaChanged = GenerateAggregateMessageMetaRegistryFile(protocolList);

            bool anyChanged = shardChanged || metaShardChanged || aggregateMsgChanged || aggregateMetaChanged;
            return anyChanged ? ScanResultState.Changed : ScanResultState.NoChange;
        }

        private static List<GeneratedFileRecord> BuildProtocolShardFiles(List<ProtocolMeta> protocolList)
        {
            if (protocolList == null)
            {
                NetLogger.LogError("LiteProtocolScanner", "BuildProtocolShardFiles failed");
                return null;
            }

            var result = new List<GeneratedFileRecord>();
            var grouped = protocolList
                .OrderBy(p => p.Id)
                .GroupBy(p => string.IsNullOrEmpty(p.FeatureKey) ? "Unknown" : p.FeatureKey);

            foreach (IGrouping<string, ProtocolMeta> group in grouped)
            {
                string featureKey = SanitizeIdentifier(group.Key);
                List<ProtocolMeta> groupList = group.OrderBy(p => p.Id).ToList();

                var idSb = new StringBuilder();
                idSb.AppendLine("// ========================================================");
                idSb.AppendLine("// 自动生成的分片协议 ID 常量表。");
                idSb.AppendLine("// ========================================================");
                idSb.AppendLine("namespace StellarNet.Lite.Shared.Generated.Protocol.MsgIds");
                idSb.AppendLine("{");
                idSb.AppendLine($"    public static class Generated_{featureKey}_MsgIds");
                idSb.AppendLine("    {");

                for (int i = 0; i < groupList.Count; i++)
                {
                    ProtocolMeta proto = groupList[i];
                    idSb.AppendLine($"        public const int {proto.SafeName} = {proto.Id};");
                }

                idSb.AppendLine("    }");
                idSb.AppendLine("}");

                result.Add(new GeneratedFileRecord
                {
                    Path = $"{ProtocolIdsFolderPath}/Generated_{featureKey}_MsgIds.cs",
                    Content = idSb.ToString()
                });

                var metaSb = new StringBuilder();
                metaSb.AppendLine("// ========================================================");
                metaSb.AppendLine("// 自动生成的分片协议元数据注册表。");
                metaSb.AppendLine("// ========================================================");
                metaSb.AppendLine("using System;");
                metaSb.AppendLine("using System.Collections.Generic;");
                metaSb.AppendLine("using StellarNet.Lite.Shared.Core;");
                metaSb.AppendLine();
                metaSb.AppendLine("namespace StellarNet.Lite.Shared.Generated.Protocol.Meta");
                metaSb.AppendLine("{");
                metaSb.AppendLine($"    public static class Generated_{featureKey}_MessageMeta");
                metaSb.AppendLine("    {");
                metaSb.AppendLine("        public static void AppendTypeToMeta(Dictionary<Type, NetMessageMeta> target)");
                metaSb.AppendLine("        {");
                metaSb.AppendLine("            if (target == null)");
                metaSb.AppendLine("            {");
                metaSb.AppendLine(
                    $"                StellarNet.Lite.Shared.Infrastructure.NetLogger.LogError(\"Generated_{featureKey}_MessageMeta\", \"AppendTypeToMeta failed\");");
                metaSb.AppendLine("                return;");
                metaSb.AppendLine("            }");

                for (int i = 0; i < groupList.Count; i++)
                {
                    ProtocolMeta proto = groupList[i];
                    metaSb.AppendLine($"            target[typeof({proto.FullTypeName})] = new NetMessageMeta({proto.Id}, NetScope.{proto.Scope}, NetDir.{proto.Dir});");
                }

                metaSb.AppendLine("        }");
                metaSb.AppendLine();
                metaSb.AppendLine("        public static void AppendMsgIdToType(Dictionary<int, Type> target)");
                metaSb.AppendLine("        {");
                metaSb.AppendLine("            if (target == null)");
                metaSb.AppendLine("            {");
                metaSb.AppendLine(
                    $"                StellarNet.Lite.Shared.Infrastructure.NetLogger.LogError(\"Generated_{featureKey}_MessageMeta\", \"AppendMsgIdToType failed\");");
                metaSb.AppendLine("                return;");
                metaSb.AppendLine("            }");

                for (int i = 0; i < groupList.Count; i++)
                {
                    ProtocolMeta proto = groupList[i];
                    metaSb.AppendLine($"            target[{proto.Id}] = typeof({proto.FullTypeName});");
                }

                metaSb.AppendLine("        }");
                metaSb.AppendLine("    }");
                metaSb.AppendLine("}");

                result.Add(new GeneratedFileRecord
                {
                    Path = $"{ProtocolMetaFolderPath}/Generated_{featureKey}_MessageMeta.cs",
                    Content = metaSb.ToString()
                });
            }

            return result;
        }

        private static bool GenerateAggregateMsgIdConstFile(List<ProtocolMeta> protocolList)
        {
            protocolList = protocolList.OrderBy(p => p.Id).ToList();

            var sb = new StringBuilder();
            sb.AppendLine("// ========================================================");
            sb.AppendLine("// 自动生成的协议 ID 常量聚合表。");
            sb.AppendLine("// ========================================================");
            sb.AppendLine("namespace StellarNet.Lite.Shared.Protocol");
            sb.AppendLine("{");
            sb.AppendLine("    public static class MsgIdConst");
            sb.AppendLine("    {");

            for (int i = 0; i < protocolList.Count; i++)
            {
                ProtocolMeta proto = protocolList[i];
                sb.AppendLine($"        public const int {proto.SafeName} = {proto.Id};");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return WriteToFileIfChanged(MsgIdAggregateOutputPath, sb.ToString());
        }

        private static bool GenerateAggregateMessageMetaRegistryFile(List<ProtocolMeta> protocolList)
        {
            protocolList = protocolList.OrderBy(p => p.Id).ToList();

            List<string> featureKeys = protocolList
                .Select(p => string.IsNullOrEmpty(p.FeatureKey) ? "Unknown" : SanitizeIdentifier(p.FeatureKey))
                .Distinct()
                .OrderBy(p => p)
                .ToList();

            var sb = new StringBuilder();
            sb.AppendLine("// ========================================================");
            sb.AppendLine("// 自动生成的协议元数据静态注册聚合表。");
            sb.AppendLine("// ========================================================");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using StellarNet.Lite.Shared.Core;");
            sb.AppendLine("using StellarNet.Lite.Shared.Generated.Protocol.Meta;");
            sb.AppendLine();
            sb.AppendLine("namespace StellarNet.Lite.Shared.Protocol");
            sb.AppendLine("{");
            sb.AppendLine("    public static class AutoMessageMetaRegistry");
            sb.AppendLine("    {");
            sb.AppendLine("        public static readonly Dictionary<Type, NetMessageMeta> TypeToMeta = BuildTypeToMeta();");
            sb.AppendLine("        public static readonly Dictionary<int, Type> MsgIdToType = BuildMsgIdToType();");
            sb.AppendLine();
            sb.AppendLine("        private static Dictionary<Type, NetMessageMeta> BuildTypeToMeta()");
            sb.AppendLine("        {");
            sb.AppendLine("            var result = new Dictionary<Type, NetMessageMeta>();");

            for (int i = 0; i < featureKeys.Count; i++)
            {
                string featureKey = featureKeys[i];
                sb.AppendLine($"            Generated_{featureKey}_MessageMeta.AppendTypeToMeta(result);");
            }

            sb.AppendLine("            return result;");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private static Dictionary<int, Type> BuildMsgIdToType()");
            sb.AppendLine("        {");
            sb.AppendLine("            var result = new Dictionary<int, Type>();");

            for (int i = 0; i < featureKeys.Count; i++)
            {
                string featureKey = featureKeys[i];
                sb.AppendLine($"            Generated_{featureKey}_MessageMeta.AppendMsgIdToType(result);");
            }

            sb.AppendLine("            return result;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            return WriteToFileIfChanged(MessageMetaAggregateOutputPath, sb.ToString());
        }

        #endregion

        #region 组件与注册扫描

        private static ScanResultState ScanAndGenerateComponentsAndRegistry()
        {
            var serverComps = new List<ClassMeta>();
            var clientComps = new List<ClassMeta>();
            var serverMods = new List<ClassMeta>();
            var clientMods = new List<ClassMeta>();

            var serverGlobalMsgIds = new Dictionary<int, string>();
            var serverRoomMsgIds = new Dictionary<int, string>();
            var clientGlobalMsgIds = new Dictionary<int, string>();
            var clientRoomMsgIds = new Dictionary<int, string>();

            bool hasFatalError = false;

            var roomCompTypes = TypeCache.GetTypesWithAttribute<RoomComponentAttribute>();
            foreach (Type type in roomCompTypes)
            {
                if (type == null)
                {
                    continue;
                }

                RoomComponentAttribute attr = type.GetCustomAttribute<RoomComponentAttribute>();
                if (attr == null)
                {
                    continue;
                }

                var meta = new ClassMeta
                {
                    Id = attr.Id,
                    Name = attr.Name,
                    SafeVarName = SanitizeIdentifier(GetCSharpTypeName(type)),
                    FullName = GetCSharpTypeName(type),
                    DisplayName = attr.DisplayName,
                    FeatureKey = GetFeatureKeyByType(type)
                };

                bool isServer = type.IsSubclassOf(typeof(StellarNet.Lite.Server.Core.RoomComponent));
                bool isClient = type.IsSubclassOf(typeof(StellarNet.Lite.Client.Core.ClientRoomComponent));

                if (!isServer && !isClient)
                {
                    NetLogger.LogError("LiteProtocolScanner", "RoomComponent base type invalid");
                    hasFatalError = true;
                    continue;
                }

                if (isServer && isClient)
                {
                    NetLogger.LogError("LiteProtocolScanner", "RoomComponent base type conflict");
                    hasFatalError = true;
                    continue;
                }

                bool methodsSafe = ScanMethods(type, isServer, meta, isServer ? serverRoomMsgIds : clientRoomMsgIds);
                if (!methodsSafe)
                {
                    hasFatalError = true;
                }

                if (isServer)
                {
                    serverComps.Add(meta);
                }
                else
                {
                    clientComps.Add(meta);
                }
            }

            var serverModTypes = TypeCache.GetTypesWithAttribute<ServerModuleAttribute>();
            foreach (Type type in serverModTypes)
            {
                if (type == null)
                {
                    continue;
                }

                ServerModuleAttribute attr = type.GetCustomAttribute<ServerModuleAttribute>();
                if (attr == null)
                {
                    continue;
                }

                var meta = new ClassMeta
                {
                    Name = attr.Name,
                    SafeVarName = SanitizeIdentifier(GetCSharpTypeName(type)),
                    FullName = GetCSharpTypeName(type),
                    DisplayName = attr.DisplayName,
                    FeatureKey = GetFeatureKeyByType(type)
                };

                if (!ScanMethods(type, true, meta, serverGlobalMsgIds))
                {
                    hasFatalError = true;
                }

                serverMods.Add(meta);
            }

            var clientModTypes = TypeCache.GetTypesWithAttribute<ClientModuleAttribute>();
            foreach (Type type in clientModTypes)
            {
                if (type == null)
                {
                    continue;
                }

                ClientModuleAttribute attr = type.GetCustomAttribute<ClientModuleAttribute>();
                if (attr == null)
                {
                    continue;
                }

                var meta = new ClassMeta
                {
                    Name = attr.Name,
                    SafeVarName = SanitizeIdentifier(GetCSharpTypeName(type)),
                    FullName = GetCSharpTypeName(type),
                    DisplayName = attr.DisplayName,
                    FeatureKey = GetFeatureKeyByType(type)
                };

                if (!ScanMethods(type, false, meta, clientGlobalMsgIds))
                {
                    hasFatalError = true;
                }

                clientMods.Add(meta);
            }

            if (!ValidateComponentMetaConsistency(serverComps, clientComps))
            {
                hasFatalError = true;
            }

            if (!ValidateComponentConstNameConflicts(serverComps, clientComps))
            {
                hasFatalError = true;
            }

            if (hasFatalError)
            {
                return ScanResultState.Failed;
            }

            List<ClassMeta> mergedComps = MergeUniqueComponentsById(serverComps, clientComps);

            List<GeneratedFileRecord> componentShardFiles = BuildComponentConstShardFiles(mergedComps);
            if (componentShardFiles == null)
            {
                return ScanResultState.Failed;
            }

            List<GeneratedFileRecord> roomBinderShardFiles = BuildRoomBinderShardFiles(serverComps, clientComps, mergedComps);
            if (roomBinderShardFiles == null)
            {
                return ScanResultState.Failed;
            }

            List<GeneratedFileRecord> moduleBinderShardFiles = BuildModuleBinderShardFiles(serverMods, clientMods);
            if (moduleBinderShardFiles == null)
            {
                return ScanResultState.Failed;
            }

            bool componentShardChanged = WriteGeneratedShardSet(ComponentConstFolderPath, componentShardFiles);
            bool roomBinderChanged = WriteGeneratedShardSet(BinderRoomFolderPath, roomBinderShardFiles);
            bool moduleBinderChanged = WriteGeneratedShardSet(BinderModuleFolderPath, moduleBinderShardFiles);

            bool componentAggregateChanged = GenerateAggregateComponentConstFile(mergedComps);
            bool registryAggregateChanged = GenerateAggregateAutoRegistryFile(serverComps, clientComps, serverMods, clientMods, mergedComps);

            bool anyChanged =
                componentShardChanged ||
                roomBinderChanged ||
                moduleBinderChanged ||
                componentAggregateChanged ||
                registryAggregateChanged;

            return anyChanged ? ScanResultState.Changed : ScanResultState.NoChange;
        }

        private static bool ScanMethods(Type type, bool isServer, ClassMeta meta, Dictionary<int, string> msgIdTracker)
        {
            if (type == null || meta == null || msgIdTracker == null)
            {
                NetLogger.LogError("LiteProtocolScanner", "ScanMethods failed");
                return false;
            }

            MethodInfo[] methods = type.GetMethods(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic);
            bool isSafe = true;

            foreach (MethodInfo method in methods)
            {
                if (method.GetCustomAttribute<NetHandlerAttribute>() == null)
                {
                    continue;
                }

                ParameterInfo[] parameters = method.GetParameters();
                Type msgType = null;

                if (isServer)
                {
                    if (parameters.Length != 2 || parameters[0].ParameterType != typeof(StellarNet.Lite.Server.Core.Session))
                    {
                        NetLogger.LogError("LiteProtocolScanner", "Server NetHandler signature invalid");
                        isSafe = false;
                        continue;
                    }

                    msgType = parameters[1].ParameterType;
                }
                else
                {
                    if (parameters.Length != 1)
                    {
                        NetLogger.LogError("LiteProtocolScanner", "Client NetHandler signature invalid");
                        isSafe = false;
                        continue;
                    }

                    msgType = parameters[0].ParameterType;
                }

                if (msgType == null)
                {
                    NetLogger.LogError("LiteProtocolScanner", "Msg type invalid");
                    isSafe = false;
                    continue;
                }

                NetMsgAttribute netMsgAttr = msgType.GetCustomAttribute<NetMsgAttribute>();
                if (netMsgAttr == null)
                {
                    NetLogger.LogError("LiteProtocolScanner", "Msg type missing NetMsg");
                    isSafe = false;
                    continue;
                }

                string currentMethodName = $"{type.FullName}.{method.Name}";
                if (msgIdTracker.TryGetValue(netMsgAttr.Id, out _))
                {
                    NetLogger.LogError("LiteProtocolScanner", $"Handler MsgId conflict: {netMsgAttr.Id}");
                    isSafe = false;
                    continue;
                }

                msgIdTracker.Add(netMsgAttr.Id, currentMethodName);

                meta.Methods.Add(new MethodMeta
                {
                    MethodName = method.Name,
                    MsgFullName = GetCSharpTypeName(msgType),
                    MsgId = netMsgAttr.Id,
                    FeatureKey = GetFeatureKeyByType(msgType)
                });
            }

            return isSafe;
        }

        private static bool ValidateComponentMetaConsistency(List<ClassMeta> serverComps, List<ClassMeta> clientComps)
        {
            bool isSafe = true;

            var serverMap = new Dictionary<int, ClassMeta>();
            for (int i = 0; i < serverComps.Count; i++)
            {
                ClassMeta meta = serverComps[i];
                if (serverMap.ContainsKey(meta.Id))
                {
                    NetLogger.LogError("LiteProtocolScanner", $"Server component id conflict: {meta.Id}");
                    isSafe = false;
                    continue;
                }

                serverMap.Add(meta.Id, meta);
            }

            var clientMap = new Dictionary<int, ClassMeta>();
            for (int i = 0; i < clientComps.Count; i++)
            {
                ClassMeta meta = clientComps[i];
                if (clientMap.ContainsKey(meta.Id))
                {
                    NetLogger.LogError("LiteProtocolScanner", $"Client component id conflict: {meta.Id}");
                    isSafe = false;
                    continue;
                }

                clientMap.Add(meta.Id, meta);
            }

            foreach (KeyValuePair<int, ClassMeta> kv in serverMap)
            {
                if (!clientMap.TryGetValue(kv.Key, out ClassMeta clientMeta))
                {
                    continue;
                }

                ClassMeta serverMeta = kv.Value;
                if (!string.Equals(serverMeta.Name, clientMeta.Name, StringComparison.Ordinal) ||
                    !string.Equals(serverMeta.DisplayName, clientMeta.DisplayName, StringComparison.Ordinal))
                {
                    NetLogger.LogError("LiteProtocolScanner", $"Component meta mismatch: {kv.Key}");
                    isSafe = false;
                }
            }

            return isSafe;
        }

        private static bool ValidateComponentConstNameConflicts(List<ClassMeta> serverComps, List<ClassMeta> clientComps)
        {
            bool isSafe = true;
            List<ClassMeta> mergedComps = MergeUniqueComponentsById(serverComps, clientComps);
            var constNameMap = new Dictionary<string, ClassMeta>();

            for (int i = 0; i < mergedComps.Count; i++)
            {
                ClassMeta meta = mergedComps[i];
                string constName = SanitizeIdentifier(meta.Name);

                if (constNameMap.TryGetValue(constName, out ClassMeta existingMeta))
                {
                    bool isSameLogicalComponent =
                        existingMeta.Id == meta.Id &&
                        string.Equals(existingMeta.Name, meta.Name, StringComparison.Ordinal);

                    if (isSameLogicalComponent)
                    {
                        continue;
                    }

                    NetLogger.LogError("LiteProtocolScanner", $"Component const conflict: {constName}");
                    isSafe = false;
                    continue;
                }

                constNameMap.Add(constName, meta);
            }

            return isSafe;
        }

        private static List<ClassMeta> MergeUniqueComponentsById(List<ClassMeta> serverComps, List<ClassMeta> clientComps)
        {
            List<ClassMeta> allComps = serverComps.Concat(clientComps).OrderBy(c => c.Id).ToList();
            var merged = new List<ClassMeta>();
            var idMap = new Dictionary<int, ClassMeta>();

            for (int i = 0; i < allComps.Count; i++)
            {
                ClassMeta meta = allComps[i];
                if (meta == null)
                {
                    continue;
                }

                if (idMap.ContainsKey(meta.Id))
                {
                    continue;
                }

                idMap.Add(meta.Id, meta);
                merged.Add(meta);
            }

            return merged;
        }

        #endregion

        #region 组件常量分片

        private static List<GeneratedFileRecord> BuildComponentConstShardFiles(List<ClassMeta> compList)
        {
            if (compList == null)
            {
                NetLogger.LogError("LiteProtocolScanner", "BuildComponentConstShardFiles failed");
                return null;
            }

            var result = new List<GeneratedFileRecord>();
            var grouped = compList
                .OrderBy(p => p.Id)
                .GroupBy(c => string.IsNullOrEmpty(c.FeatureKey) ? "Unknown" : c.FeatureKey);

            foreach (IGrouping<string, ClassMeta> group in grouped)
            {
                string featureKey = SanitizeIdentifier(group.Key);
                List<ClassMeta> groupList = group.OrderBy(c => c.Id).ToList();

                var sb = new StringBuilder();
                sb.AppendLine("// ========================================================");
                sb.AppendLine("// 自动生成的分片组件 ID 常量表。");
                sb.AppendLine("// ========================================================");
                sb.AppendLine("namespace StellarNet.Lite.Shared.Generated.Protocol.Components");
                sb.AppendLine("{");
                sb.AppendLine($"    public static class Generated_{featureKey}_ComponentIds");
                sb.AppendLine("    {");

                for (int i = 0; i < groupList.Count; i++)
                {
                    ClassMeta comp = groupList[i];
                    sb.AppendLine($"        public const int {SanitizeIdentifier(comp.Name)} = {comp.Id};");
                }

                sb.AppendLine("    }");
                sb.AppendLine("}");

                result.Add(new GeneratedFileRecord
                {
                    Path = $"{ComponentConstFolderPath}/Generated_{featureKey}_ComponentIds.cs",
                    Content = sb.ToString()
                });
            }

            return result;
        }

        private static bool GenerateAggregateComponentConstFile(List<ClassMeta> compList)
        {
            compList = compList.OrderBy(p => p.Id).ToList();

            var sb = new StringBuilder();
            sb.AppendLine("// ========================================================");
            sb.AppendLine("// 自动生成的组件 ID 常量聚合表。");
            sb.AppendLine("// ========================================================");
            sb.AppendLine("namespace StellarNet.Lite.Shared.Protocol");
            sb.AppendLine("{");
            sb.AppendLine("    public static class ComponentIdConst");
            sb.AppendLine("    {");

            for (int i = 0; i < compList.Count; i++)
            {
                ClassMeta comp = compList[i];
                sb.AppendLine($"        public const int {SanitizeIdentifier(comp.Name)} = {comp.Id};");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return WriteToFileIfChanged(ComponentAggregateOutputPath, sb.ToString());
        }

        #endregion

        #region RoomBinder 分片

        private static List<GeneratedFileRecord> BuildRoomBinderShardFiles(
            List<ClassMeta> serverComps,
            List<ClassMeta> clientComps,
            List<ClassMeta> mergedComps)
        {
            if (serverComps == null || clientComps == null || mergedComps == null)
            {
                NetLogger.LogError("LiteProtocolScanner", "BuildRoomBinderShardFiles failed");
                return null;
            }

            var result = new List<GeneratedFileRecord>();
            var featureKeys = mergedComps
                .Select(c => string.IsNullOrEmpty(c.FeatureKey) ? "Unknown" : SanitizeIdentifier(c.FeatureKey))
                .Distinct()
                .OrderBy(k => k)
                .ToList();

            for (int i = 0; i < featureKeys.Count; i++)
            {
                string featureKey = featureKeys[i];
                List<ClassMeta> featureMergedComps = mergedComps.Where(c => SanitizeIdentifier(c.FeatureKey) == featureKey).OrderBy(c => c.Id).ToList();
                List<ClassMeta> featureServerComps = serverComps.Where(c => SanitizeIdentifier(c.FeatureKey) == featureKey).OrderBy(c => c.Id).ToList();
                List<ClassMeta> featureClientComps = clientComps.Where(c => SanitizeIdentifier(c.FeatureKey) == featureKey).OrderBy(c => c.Id).ToList();

                var sb = new StringBuilder();
                sb.AppendLine("// ========================================================");
                sb.AppendLine("// 自动生成的房间组件绑定分片。");
                sb.AppendLine("// ========================================================");
                sb.AppendLine("using System;");
                sb.AppendLine("using System.Collections.Generic;");
                sb.AppendLine("using StellarNet.Lite.Shared.Core;");
                sb.AppendLine("using StellarNet.Lite.Server.Core;");
                sb.AppendLine("using StellarNet.Lite.Client.Core;");
                sb.AppendLine();
                sb.AppendLine("namespace StellarNet.Lite.Shared.Generated.Binders.RoomComponents");
                sb.AppendLine("{");
                sb.AppendLine($"    public static class Generated_{featureKey}_RoomBinder");
                sb.AppendLine("    {");
                sb.AppendLine("        public static void AppendRoomComponentMeta(List<RoomComponentMeta> target)");
                sb.AppendLine("        {");
                sb.AppendLine("            if (target == null)");
                sb.AppendLine("            {");
                sb.AppendLine(
                    $"                StellarNet.Lite.Shared.Infrastructure.NetLogger.LogError(\"Generated_{featureKey}_RoomBinder\", \"AppendRoomComponentMeta failed\");");
                sb.AppendLine("                return;");
                sb.AppendLine("            }");

                for (int j = 0; j < featureMergedComps.Count; j++)
                {
                    ClassMeta comp = featureMergedComps[j];
                    sb.AppendLine(
                        $"            target.Add(new RoomComponentMeta {{ Id = {comp.Id}, Name = \"{EscapeStringLiteral(comp.Name)}\", DisplayName = \"{EscapeStringLiteral(comp.DisplayName)}\" }});");
                }

                sb.AppendLine("        }");
                sb.AppendLine();
                sb.AppendLine("        public static void RegisterServerFactory(ServerApp serverApp)");
                sb.AppendLine("        {");
                sb.AppendLine("            if (serverApp == null)");
                sb.AppendLine("            {");
                sb.AppendLine(
                    $"                StellarNet.Lite.Shared.Infrastructure.NetLogger.LogError(\"Generated_{featureKey}_RoomBinder\", \"RegisterServerFactory failed\");");
                sb.AppendLine("                return;");
                sb.AppendLine("            }");

                for (int j = 0; j < featureServerComps.Count; j++)
                {
                    ClassMeta comp = featureServerComps[j];
                    sb.AppendLine($"            ServerRoomFactory.Register({comp.Id}, () => new {comp.FullName}(serverApp));");
                }

                sb.AppendLine("        }");
                sb.AppendLine();
                sb.AppendLine("        public static void RegisterClientFactory(ClientApp clientApp)");
                sb.AppendLine("        {");
                sb.AppendLine("            if (clientApp == null)");
                sb.AppendLine("            {");
                sb.AppendLine(
                    $"                StellarNet.Lite.Shared.Infrastructure.NetLogger.LogError(\"Generated_{featureKey}_RoomBinder\", \"RegisterClientFactory failed\");");
                sb.AppendLine("                return;");
                sb.AppendLine("            }");

                for (int j = 0; j < featureClientComps.Count; j++)
                {
                    ClassMeta comp = featureClientComps[j];
                    sb.AppendLine($"            ClientRoomFactory.Register({comp.Id}, () => new {comp.FullName}(clientApp));");
                }

                sb.AppendLine("        }");
                sb.AppendLine();
                sb.AppendLine(
                    "        public static bool TryBindServer(StellarNet.Lite.Server.Core.RoomComponent comp, StellarNet.Lite.Server.Core.RoomDispatcher dispatcher, Func<byte[], int, int, Type, object> deserializeFunc)");
                sb.AppendLine("        {");
                sb.AppendLine("            if (comp == null || dispatcher == null || deserializeFunc == null)");
                sb.AppendLine("            {");
                sb.AppendLine($"                StellarNet.Lite.Shared.Infrastructure.NetLogger.LogError(\"Generated_{featureKey}_RoomBinder\", \"TryBindServer failed\");");
                sb.AppendLine("                return false;");
                sb.AppendLine("            }");
                sb.AppendLine("            switch (comp)");
                sb.AppendLine("            {");

                for (int j = 0; j < featureServerComps.Count; j++)
                {
                    ClassMeta comp = featureServerComps[j];
                    sb.AppendLine($"                case {comp.FullName} c_{comp.Id}:");

                    for (int k = 0; k < comp.Methods.Count; k++)
                    {
                        MethodMeta method = comp.Methods[k];
                        sb.AppendLine($"                    dispatcher.Register({method.MsgId}, (session, packet) => {{");
                        sb.AppendLine(
                            $"                        if (deserializeFunc(packet.Payload, packet.PayloadOffset, packet.PayloadLength, typeof({method.MsgFullName})) is {method.MsgFullName} msg) {{");
                        sb.AppendLine($"                            c_{comp.Id}.{method.MethodName}(session, msg);");
                        sb.AppendLine("                        }");
                        sb.AppendLine("                        else");
                        sb.AppendLine("                        {");
                        sb.AppendLine(
                            $"                            StellarNet.Lite.Shared.Infrastructure.NetLogger.LogError(\"Generated_{featureKey}_RoomBinder\", \"Deserialize failed\");");
                        sb.AppendLine("                        }");
                        sb.AppendLine("                    });");
                    }

                    sb.AppendLine("                    return true;");
                }

                sb.AppendLine("            }");
                sb.AppendLine("            return false;");
                sb.AppendLine("        }");
                sb.AppendLine();
                sb.AppendLine(
                    "        public static bool TryBindClient(StellarNet.Lite.Client.Core.ClientRoomComponent comp, StellarNet.Lite.Client.Core.ClientRoomDispatcher dispatcher, Func<byte[], int, int, Type, object> deserializeFunc)");
                sb.AppendLine("        {");
                sb.AppendLine("            if (comp == null || dispatcher == null || deserializeFunc == null)");
                sb.AppendLine("            {");
                sb.AppendLine($"                StellarNet.Lite.Shared.Infrastructure.NetLogger.LogError(\"Generated_{featureKey}_RoomBinder\", \"TryBindClient failed\");");
                sb.AppendLine("                return false;");
                sb.AppendLine("            }");
                sb.AppendLine("            switch (comp)");
                sb.AppendLine("            {");

                for (int j = 0; j < featureClientComps.Count; j++)
                {
                    ClassMeta comp = featureClientComps[j];
                    sb.AppendLine($"                case {comp.FullName} c_{comp.Id}:");

                    for (int k = 0; k < comp.Methods.Count; k++)
                    {
                        MethodMeta method = comp.Methods[k];
                        sb.AppendLine($"                    dispatcher.Register({method.MsgId}, (packet) => {{");
                        sb.AppendLine(
                            $"                        if (deserializeFunc(packet.Payload, packet.PayloadOffset, packet.PayloadLength, typeof({method.MsgFullName})) is {method.MsgFullName} msg) {{");
                        sb.AppendLine($"                            c_{comp.Id}.{method.MethodName}(msg);");
                        sb.AppendLine("                        }");
                        sb.AppendLine("                        else");
                        sb.AppendLine("                        {");
                        sb.AppendLine(
                            $"                            StellarNet.Lite.Shared.Infrastructure.NetLogger.LogError(\"Generated_{featureKey}_RoomBinder\", \"Deserialize failed\");");
                        sb.AppendLine("                        }");
                        sb.AppendLine("                    });");
                    }

                    sb.AppendLine("                    return true;");
                }

                sb.AppendLine("            }");
                sb.AppendLine("            return false;");
                sb.AppendLine("        }");
                sb.AppendLine("    }");
                sb.AppendLine("}");

                result.Add(new GeneratedFileRecord
                {
                    Path = $"{BinderRoomFolderPath}/Generated_{featureKey}_RoomBinder.cs",
                    Content = sb.ToString()
                });
            }

            return result;
        }

        #endregion

        #region ModuleBinder 分片

        private static List<GeneratedFileRecord> BuildModuleBinderShardFiles(List<ClassMeta> serverMods, List<ClassMeta> clientMods)
        {
            if (serverMods == null || clientMods == null)
            {
                NetLogger.LogError("LiteProtocolScanner", "BuildModuleBinderShardFiles failed");
                return null;
            }

            var result = new List<GeneratedFileRecord>();
            List<string> featureKeys = serverMods.Concat(clientMods)
                .Select(m => string.IsNullOrEmpty(m.FeatureKey) ? "Unknown" : SanitizeIdentifier(m.FeatureKey))
                .Distinct()
                .OrderBy(k => k)
                .ToList();

            foreach (string featureKey in featureKeys)
            {
                List<ClassMeta> featureServerMods = serverMods.Where(m => SanitizeIdentifier(m.FeatureKey) == featureKey).OrderBy(m => m.FullName).ToList();
                List<ClassMeta> featureClientMods = clientMods.Where(m => SanitizeIdentifier(m.FeatureKey) == featureKey).OrderBy(m => m.FullName).ToList();

                var sb = new StringBuilder();
                sb.AppendLine("// ========================================================");
                sb.AppendLine("// 自动生成的全局模块绑定分片。");
                sb.AppendLine("// ========================================================");
                sb.AppendLine("using System;");
                sb.AppendLine("using StellarNet.Lite.Server.Core;");
                sb.AppendLine("using StellarNet.Lite.Client.Core;");
                sb.AppendLine();
                sb.AppendLine("namespace StellarNet.Lite.Shared.Generated.Binders.GlobalModules");
                sb.AppendLine("{");
                sb.AppendLine($"    public static class Generated_{featureKey}_ModuleBinder");
                sb.AppendLine("    {");
                sb.AppendLine("        public static void RegisterServer(ServerApp serverApp, Func<byte[], int, int, Type, object> deserializeFunc)");
                sb.AppendLine("        {");
                sb.AppendLine("            if (serverApp == null || deserializeFunc == null)");
                sb.AppendLine("            {");
                sb.AppendLine($"                StellarNet.Lite.Shared.Infrastructure.NetLogger.LogError(\"Generated_{featureKey}_ModuleBinder\", \"RegisterServer failed\");");
                sb.AppendLine("                return;");
                sb.AppendLine("            }");

                for (int i = 0; i < featureServerMods.Count; i++)
                {
                    ClassMeta mod = featureServerMods[i];
                    sb.AppendLine($"            var mod_{mod.SafeVarName} = new {mod.FullName}(serverApp);");

                    for (int j = 0; j < mod.Methods.Count; j++)
                    {
                        MethodMeta method = mod.Methods[j];
                        sb.AppendLine($"            serverApp.GlobalDispatcher.Register({method.MsgId}, (session, packet) => {{");
                        sb.AppendLine(
                            $"                if (deserializeFunc(packet.Payload, packet.PayloadOffset, packet.PayloadLength, typeof({method.MsgFullName})) is {method.MsgFullName} msg) {{");
                        sb.AppendLine($"                    mod_{mod.SafeVarName}.{method.MethodName}(session, msg);");
                        sb.AppendLine("                }");
                        sb.AppendLine("                else");
                        sb.AppendLine("                {");
                        sb.AppendLine(
                            $"                    StellarNet.Lite.Shared.Infrastructure.NetLogger.LogError(\"Generated_{featureKey}_ModuleBinder\", \"Deserialize failed\");");
                        sb.AppendLine("                }");
                        sb.AppendLine("            });");
                    }
                }

                sb.AppendLine("        }");
                sb.AppendLine();
                sb.AppendLine("        public static void RegisterClient(ClientApp clientApp, Func<byte[], int, int, Type, object> deserializeFunc)");
                sb.AppendLine("        {");
                sb.AppendLine("            if (clientApp == null || deserializeFunc == null)");
                sb.AppendLine("            {");
                sb.AppendLine($"                StellarNet.Lite.Shared.Infrastructure.NetLogger.LogError(\"Generated_{featureKey}_ModuleBinder\", \"RegisterClient failed\");");
                sb.AppendLine("                return;");
                sb.AppendLine("            }");

                for (int i = 0; i < featureClientMods.Count; i++)
                {
                    ClassMeta mod = featureClientMods[i];
                    sb.AppendLine($"            var mod_{mod.SafeVarName} = new {mod.FullName}(clientApp);");

                    for (int j = 0; j < mod.Methods.Count; j++)
                    {
                        MethodMeta method = mod.Methods[j];
                        sb.AppendLine($"            clientApp.GlobalDispatcher.Register({method.MsgId}, (packet) => {{");
                        sb.AppendLine(
                            $"                if (deserializeFunc(packet.Payload, packet.PayloadOffset, packet.PayloadLength, typeof({method.MsgFullName})) is {method.MsgFullName} msg) {{");
                        sb.AppendLine($"                    mod_{mod.SafeVarName}.{method.MethodName}(msg);");
                        sb.AppendLine("                }");
                        sb.AppendLine("                else");
                        sb.AppendLine("                {");
                        sb.AppendLine(
                            $"                    StellarNet.Lite.Shared.Infrastructure.NetLogger.LogError(\"Generated_{featureKey}_ModuleBinder\", \"Deserialize failed\");");
                        sb.AppendLine("                }");
                        sb.AppendLine("            });");
                    }
                }

                sb.AppendLine("        }");
                sb.AppendLine("    }");
                sb.AppendLine("}");

                result.Add(new GeneratedFileRecord
                {
                    Path = $"{BinderModuleFolderPath}/Generated_{featureKey}_ModuleBinder.cs",
                    Content = sb.ToString()
                });
            }

            return result;
        }

        #endregion

        #region 聚合 AutoRegistry

        private static bool GenerateAggregateAutoRegistryFile(
            List<ClassMeta> serverComps,
            List<ClassMeta> clientComps,
            List<ClassMeta> serverMods,
            List<ClassMeta> clientMods,
            List<ClassMeta> mergedComps)
        {
            List<string> roomFeatureKeys = mergedComps
                .Select(c => string.IsNullOrEmpty(c.FeatureKey) ? "Unknown" : SanitizeIdentifier(c.FeatureKey))
                .Distinct()
                .OrderBy(k => k)
                .ToList();

            List<string> moduleFeatureKeys = serverMods.Concat(clientMods)
                .Select(m => string.IsNullOrEmpty(m.FeatureKey) ? "Unknown" : SanitizeIdentifier(m.FeatureKey))
                .Distinct()
                .OrderBy(k => k)
                .ToList();

            var sb = new StringBuilder();
            sb.AppendLine("// ========================================================");
            sb.AppendLine("// 自动生成的静态装配聚合器。");
            sb.AppendLine("// ========================================================");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using StellarNet.Lite.Shared.Core;");
            sb.AppendLine("using StellarNet.Lite.Server.Core;");
            sb.AppendLine("using StellarNet.Lite.Client.Core;");
            sb.AppendLine("using StellarNet.Lite.Shared.Generated.Binders.RoomComponents;");
            sb.AppendLine("using StellarNet.Lite.Shared.Generated.Binders.GlobalModules;");
            sb.AppendLine();
            sb.AppendLine("namespace StellarNet.Lite.Shared.Binders");
            sb.AppendLine("{");
            sb.AppendLine("    public static class AutoRegistry");
            sb.AppendLine("    {");
            sb.AppendLine("        public static readonly List<RoomComponentMeta> RoomComponentMetaList = BuildRoomComponentMetaList();");
            sb.AppendLine();
            sb.AppendLine("        private static List<RoomComponentMeta> BuildRoomComponentMetaList()");
            sb.AppendLine("        {");
            sb.AppendLine("            var result = new List<RoomComponentMeta>();");

            for (int i = 0; i < roomFeatureKeys.Count; i++)
            {
                string featureKey = roomFeatureKeys[i];
                sb.AppendLine($"            Generated_{featureKey}_RoomBinder.AppendRoomComponentMeta(result);");
            }

            sb.AppendLine("            return result;");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public static void RegisterServer(ServerApp serverApp, Func<byte[], int, int, Type, object> deserializeFunc)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (serverApp == null || deserializeFunc == null)");
            sb.AppendLine("            {");
            sb.AppendLine("                StellarNet.Lite.Shared.Infrastructure.NetLogger.LogError(\"AutoRegistry\", \"RegisterServer failed\");");
            sb.AppendLine("                return;");
            sb.AppendLine("            }");
            sb.AppendLine("            ServerRoomFactory.Clear();");

            for (int i = 0; i < moduleFeatureKeys.Count; i++)
            {
                string featureKey = moduleFeatureKeys[i];
                sb.AppendLine($"            Generated_{featureKey}_ModuleBinder.RegisterServer(serverApp, deserializeFunc);");
            }

            for (int i = 0; i < roomFeatureKeys.Count; i++)
            {
                string featureKey = roomFeatureKeys[i];
                sb.AppendLine($"            Generated_{featureKey}_RoomBinder.RegisterServerFactory(serverApp);");
            }

            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine(
                "        public static void BindServerComponent(StellarNet.Lite.Server.Core.RoomComponent comp, StellarNet.Lite.Server.Core.RoomDispatcher dispatcher, Func<byte[], int, int, Type, object> deserializeFunc)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (comp == null)");
            sb.AppendLine("            {");
            sb.AppendLine("                StellarNet.Lite.Shared.Infrastructure.NetLogger.LogError(\"AutoRegistry\", \"BindServerComponent failed\");");
            sb.AppendLine("                return;");
            sb.AppendLine("            }");

            for (int i = 0; i < roomFeatureKeys.Count; i++)
            {
                string featureKey = roomFeatureKeys[i];
                sb.AppendLine($"            if (Generated_{featureKey}_RoomBinder.TryBindServer(comp, dispatcher, deserializeFunc))");
                sb.AppendLine("            {");
                sb.AppendLine("                return;");
                sb.AppendLine("            }");
            }

            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public static void RegisterClient(ClientApp clientApp, Func<byte[], int, int, Type, object> deserializeFunc)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (clientApp == null || deserializeFunc == null)");
            sb.AppendLine("            {");
            sb.AppendLine("                StellarNet.Lite.Shared.Infrastructure.NetLogger.LogError(\"AutoRegistry\", \"RegisterClient failed\");");
            sb.AppendLine("                return;");
            sb.AppendLine("            }");
            sb.AppendLine("            ClientRoomFactory.Clear();");

            for (int i = 0; i < moduleFeatureKeys.Count; i++)
            {
                string featureKey = moduleFeatureKeys[i];
                sb.AppendLine($"            Generated_{featureKey}_ModuleBinder.RegisterClient(clientApp, deserializeFunc);");
            }

            for (int i = 0; i < roomFeatureKeys.Count; i++)
            {
                string featureKey = roomFeatureKeys[i];
                sb.AppendLine($"            Generated_{featureKey}_RoomBinder.RegisterClientFactory(clientApp);");
            }

            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine(
                "        public static void BindClientComponent(StellarNet.Lite.Client.Core.ClientRoomComponent comp, StellarNet.Lite.Client.Core.ClientRoomDispatcher dispatcher, Func<byte[], int, int, Type, object> deserializeFunc)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (comp == null)");
            sb.AppendLine("            {");
            sb.AppendLine("                StellarNet.Lite.Shared.Infrastructure.NetLogger.LogError(\"AutoRegistry\", \"BindClientComponent failed\");");
            sb.AppendLine("                return;");
            sb.AppendLine("            }");

            for (int i = 0; i < roomFeatureKeys.Count; i++)
            {
                string featureKey = roomFeatureKeys[i];
                sb.AppendLine($"            if (Generated_{featureKey}_RoomBinder.TryBindClient(comp, dispatcher, deserializeFunc))");
                sb.AppendLine("            {");
                sb.AppendLine("                return;");
                sb.AppendLine("            }");
            }

            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            return WriteToFileIfChanged(RegistryAggregateOutputPath, sb.ToString());
        }

        #endregion

        #region 分片写入与清理

        private static bool WriteGeneratedShardSet(string folderPath, List<GeneratedFileRecord> records)
        {
            if (string.IsNullOrEmpty(folderPath) || records == null)
            {
                NetLogger.LogError("LiteProtocolScanner", "WriteGeneratedShardSet failed");
                return false;
            }

            EnsureDirectoryExists(folderPath);

            bool changed = false;
            var expectedPaths = new HashSet<string>(records.Select(r => NormalizePath(r.Path)));

            string[] oldFiles = Directory.Exists(folderPath)
                ? Directory.GetFiles(folderPath, "*.cs", SearchOption.TopDirectoryOnly)
                : Array.Empty<string>();

            for (int i = 0; i < oldFiles.Length; i++)
            {
                string oldFile = NormalizePath(oldFiles[i]);
                if (expectedPaths.Contains(oldFile))
                {
                    continue;
                }

                File.Delete(oldFile);
                string metaPath = oldFile + ".meta";
                if (File.Exists(metaPath))
                {
                    File.Delete(metaPath);
                }

                changed = true;
            }

            for (int i = 0; i < records.Count; i++)
            {
                GeneratedFileRecord record = records[i];
                if (record == null)
                {
                    NetLogger.LogError("LiteProtocolScanner", "WriteGeneratedShardSet failed");
                    continue;
                }

                bool fileChanged = WriteToFileIfChanged(record.Path, record.Content);
                if (fileChanged)
                {
                    changed = true;
                }
            }

            return changed;
        }

        private static void EnsureDirectoryExists(string folderPath)
        {
            if (string.IsNullOrEmpty(folderPath))
            {
                NetLogger.LogError("LiteProtocolScanner", "EnsureDirectoryExists failed");
                return;
            }

            if (!Directory.Exists(folderPath))
            {
                Directory.CreateDirectory(folderPath);
            }
        }

        private static string NormalizePath(string path)
        {
            if (string.IsNullOrEmpty(path))
            {
                return string.Empty;
            }

            return path.Replace("\\", "/");
        }

        #endregion

        #region 文件写入

        private static bool WriteToFileIfChanged(string path, string newContent)
        {
            if (string.IsNullOrEmpty(path) || newContent == null)
            {
                NetLogger.LogError("LiteProtocolScanner", "WriteToFileIfChanged failed");
                return false;
            }

            string normalizedPath = NormalizePath(path);
            string oldContent = File.Exists(normalizedPath) ? File.ReadAllText(normalizedPath) : string.Empty;
            if (newContent == oldContent)
            {
                return false;
            }

            string directory = Path.GetDirectoryName(normalizedPath);
            if (string.IsNullOrEmpty(directory))
            {
                NetLogger.LogError("LiteProtocolScanner", "WriteToFileIfChanged failed");
                return false;
            }

            if (!Directory.Exists(directory))
            {
                Directory.CreateDirectory(directory);
            }

            File.WriteAllText(normalizedPath, newContent, Encoding.UTF8);
            return true;
        }

        #endregion
    }
}
#endif